#!/usr/bin/env zsh
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
  echo "stow $folder"
  stow --adopt -R $folder -t $HOME --no-folding
done
popd

pushd "$DOTFILES/meeopp"
./stow
popd

