#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,tmux,zsh,nvim,vim,yabai,skhd"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/personal/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
