return {
  -- {
  --   "zbirenbaum/copilot.lua",
  --   event = "InsertEnter",
  --   cmd = "Copilot",
  --   build = ":Copilot auth",
  --   opts = {
  --     suggestion = { enabled = false },
  --     panel = { enabled = false },
  --     filetypes = {
  --       markdown = true,
  --     },
  --   },
  -- },
  -- {
  --   "nvim-cmp",
  --   dependencies = {
  --     {
  --       "zbirenbaum/copilot-cmp",
  --       event = "InsertEnter",
  --       dependencies = {
  --         "zbirenbaum/copilot.lua",
  --       },
  --       opts = {},
  --       config = function(_, opts)
  --         local copilot_cmp = require("copilot_cmp")
  --
  --         copilot_cmp.setup(opts)
  --
  --         local function on_attach(attach)
  --           vim.api.nvim_create_autocmd("LspAttach", {
  --             callback = function(args)
  --               local buffer = args.buf
  --               local client = vim.lsp.get_client_by_id(args.data.client_id)
  --               attach(client, buffer)
  --             end,
  --           })
  --         end
  --
  --         on_attach(function(client)
  --           if client.name == "copilot" then
  --             copilot_cmp._on_insert_enter({})
  --           end
  --         end)
  --       end,
  --     },
  --   },
  --   opts = function(_, opts)
  --     local cmp = require("cmp")
  --
  --     opts.sorting = {
  --       priority_weight = 2,
  --       comparators = {
  --         require("copilot_cmp.comparators").prioritize,
  --         cmp.config.compare.offset,
  --         cmp.config.compare.exact,
  --         cmp.config.compare.score,
  --         cmp.config.compare.kind,
  --         cmp.config.compare.sort_text,
  --         cmp.config.compare.length,
  --         cmp.config.compare.order,
  --       },
  --     }
  --   end,
  -- },
}
